import Head from 'next/head'
import Link from "next/link";

import conectarDB from '../config/dbConfig';
import Movie from '../models/Movie';


export default function Home({ movies }) {
  console.log(movies)

  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container">
        <h1>Movies</h1>
        <Link href="/new">
          <a className="btn btn-primary w-100 mb-2">Agregar</a>
        </Link>
        {/*si le pongo parentesis hace el return, si le pongo {} no retona y no funciona*/}
        {movies.map(({ _id, title, plot }) => (
          <div className="card mb-2" key={_id}>
            <div className="card-body">
              <div className="h5 text-uppercase">
                {title}
              </div>
              <p className="fw-light">
                {plot}
              </p>
              <Link href={`/${_id}`}>
                <a className="btn btn-success btn-sm">Más info...</a>
              </Link>
            </div>
          </div>
        ))}
      </main>

    </div>
  )
}

//renderizando en el servidor.  Hace que el servidor nos traiga la info y lo pinte en el sitio web, asi se mejora el SEO (por ejemplo un  blog y el detalle de sus posts, que sí necesitan SEO)
//SWR es el navegador quien va a traer la info y las va pintar por lo tanto no va a ver mucho SEO (por ejemplo un panel de administrador, que no necesita SEO)
//dentro de esta función no se puede utiliza rel fetch para consumir nuestra propia API, de la next (archivo api) entonces se hce la conexión directa con la BBDD y se le pide lo que se necesite
export async function getServerSideProps() {
  try {
    await conectarDB() //conexion BBDD
    const res = await Movie.find({}) //Le pedimos todas las pelis
    // console.log(res) 
    
    const movies = res.map(item => {
      const oneMovie = item.toObject() //guardo en onMovie un obj clave-valor
      // console.log(oneMovie)
      
      //como el _id de mongo es un número, lo vamos a convertir a string
      //oneMovie._id = `${oneMovie._id}` esta sintaxis convierte un number en string, es lo mismo que la siguiente línea

      oneMovie._id = oneMovie._id.toString() //convierte a string

      return oneMovie //muy importante el return!!!!

    })


    return {
      props: { movies: movies } //muy importante hacer este return así!!! con las props
    }
  }
  catch (error) {
    console.log(error)
    return {
      props: { success: false, error: 'Error' } //muy importante hacer este return así!!! con las props
    }
  }


}
